#!/usr/bin/env bash
# AStock 一键安装/配置（不修改业务代码，仅创建 venv、依赖、PM2/systemd）
# 请先: bash deploy/probe_server.sh
# 再:   bash deploy/install_astock.sh --mode auto
#
# 选项:
#   --mode auto|pm2|systemd|venv-only
#   --app-root PATH
#   --port 8765
#   --host 127.0.0.1|0.0.0.0
#   --storage PATH
#   --market-data-root PATH
#   --tdx-root PATH
#   --skip-pip
#   --dry-run

set -euo pipefail

MODE="auto"
APP_ROOT=""
PORT=8765
HOST="127.0.0.1"
STORAGE=""
MARKET_DATA_ROOT_VAL=""
TDX_ROOT=""
SKIP_PIP=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="${2:-auto}"; shift 2 ;;
    --app-root) APP_ROOT="${2:-}"; shift 2 ;;
    --port) PORT="${2:-8765}"; shift 2 ;;
    --host) HOST="${2:-127.0.0.1}"; shift 2 ;;
    --storage) STORAGE="${2:-}"; shift 2 ;;
    --market-data-root) MARKET_DATA_ROOT_VAL="${2:-}"; shift 2 ;;
    --tdx-root) TDX_ROOT="${2:-}"; shift 2 ;;
    --skip-pip) SKIP_PIP=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help)
      sed -n '1,20p' "$0"
      exit 0
      ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -z "$APP_ROOT" ]]; then
  APP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi
APP_ROOT="$(cd "$APP_ROOT" && pwd)"

if [[ ! -f "$APP_ROOT/wtpy/apps/astock/__main__.py" ]]; then
  echo "[FAIL] 不是有效的 wtpy 仓库根: $APP_ROOT"
  exit 1
fi

if [[ -z "$STORAGE" ]]; then
  STORAGE="$APP_ROOT/storage/astock"
fi

ENV_FILE="$APP_ROOT/deploy/astock.env"
PM2_ECO="$APP_ROOT/deploy/ecosystem.config.cjs"
UNIT_OUT="$APP_ROOT/deploy/astock-serve.service"

run() {
  if [[ $DRY_RUN -eq 1 ]]; then
    echo "[dry-run] $*"
  else
    echo "[run] $*"
    eval "$@"
  fi
}

pick_python() {
  local c
  for c in python3.10 python3.9 python3.11 python3 python3.12 python3.8; do
    if command -v "$c" >/dev/null 2>&1; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

echo "======== AStock install ========"
echo "APP_ROOT=$APP_ROOT"
echo "MODE=$MODE PORT=$PORT HOST=$HOST"
echo "STORAGE=$STORAGE"

# ---- decide mode ----
if [[ "$MODE" == "auto" ]]; then
  if command -v pm2 >/dev/null 2>&1; then
    MODE="pm2"
    echo "[auto] 检测到 PM2 -> mode=pm2"
  elif command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
    MODE="systemd"
    echo "[auto] 检测到 systemd -> mode=systemd"
  else
    MODE="venv-only"
    echo "[auto] 无 PM2/systemd -> mode=venv-only（仅装依赖，手动启动）"
  fi
fi

# ---- python venv ----
PY_BIN="$(pick_python || true)"
if [[ -z "${PY_BIN:-}" ]]; then
  echo "[FAIL] 需要 python3"
  exit 1
fi
echo "[INFO] base python: $PY_BIN ($("$PY_BIN" --version 2>&1))"

VENV="$APP_ROOT/.venv"
if [[ ! -x "$VENV/bin/python" ]]; then
  run "\"$PY_BIN\" -m venv \"$VENV\""
fi
PIP="$VENV/bin/pip"
PY="$VENV/bin/python"

if [[ $SKIP_PIP -eq 0 ]]; then
  run "\"$PIP\" install -U pip setuptools wheel"
  # 阿里云常用镜像，失败可重试官方
  if ! run "\"$PIP\" install -r \"$APP_ROOT/requirements.txt\" -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com"; then
    echo "[WARN] 阿里云镜像失败，改用默认 PyPI"
    run "\"$PIP\" install -r \"$APP_ROOT/requirements.txt\""
  fi
  # 可编辑安装；失败则依赖 PYTHONPATH
  if ! run "\"$PIP\" install -e \"$APP_ROOT\""; then
    echo "[WARN] pip install -e 失败，将使用 PYTHONPATH=$APP_ROOT"
  fi
else
  echo "[INFO] 跳过 pip install"
fi

# ---- env file ----
mkdir -p "$APP_ROOT/deploy" "$APP_ROOT/outputs/astock"
cat >"$ENV_FILE" <<EOF
# generated by install_astock.sh — 可手工改，勿提交密钥
ASTOCK_APP_ROOT=$APP_ROOT
ASTOCK_HOST=$HOST
ASTOCK_PORT=$PORT
ASTOCK_STORAGE=$STORAGE
ASTOCK_TDX_ROOT=${TDX_ROOT}
PYTHONPATH=$APP_ROOT
TZ=Asia/Shanghai

# 正式行情数据根（serve() 与迁移脚本均读取；production 下缺失将拒绝启动）
MARKET_DATA_ROOT=${MARKET_DATA_ROOT_VAL}

# ---- overlay_v1 增量存储（推荐）----
# 置为 overlay_v1 后每周五 EOD 走 delta 写入 + 虚拟 L1/L2，不再周期性重写完整行情。
# 启用前必须先运行: python scripts/migrate_market_data_overlay.py --apply
# ASTOCK_MARKET_STORAGE_MODE=overlay_v1

# ---- 每周五 18:30 行情更新，成功后自动 consolidation/retention/Blob GC ----
ASTOCK_EOD_SYNC_ENABLED=1
ASTOCK_EOD_SYNC_STARTUP=1
ASTOCK_EOD_SYNC_TIME=18:30
ASTOCK_EOD_SYNC_WEEKDAY=4
ASTOCK_EOD_SYNC_INDEX_ETF=0
ASTOCK_EOD_SYNC_MIN_LAG_DAYS=1
ASTOCK_EOD_SYNC_POLL_SECONDS=300
ASTOCK_EOD_SYNC_MAX_RETRIES=2

# ---- 本地磁盘长期治理（不依赖 NAS）----
ASTOCK_MARKET_GOVERNANCE_ENABLED=1
ASTOCK_RETENTION_GENERATIONS=2
ASTOCK_RETENTION_GRACE_DAYS=7
ASTOCK_LEGACY_RETENTION_ENABLED=1
ASTOCK_LEGACY_KEEP_PER_FAMILY=1
ASTOCK_LEGACY_MIGRATION_GRACE_DAYS=14
ASTOCK_LEGACY_MANIFEST_MIN_AGE_DAYS=7
ASTOCK_CONSOLIDATE_TRADING_DAYS=60
ASTOCK_CONSOLIDATE_DELTA_BYTES=536870912
ASTOCK_CONSOLIDATE_MIN_FREE_GB=5
ASTOCK_CONSOLIDATE_MAX_DISK_USAGE_PCT=80

# ---- CA 公司行为（安排在周五行情更新之后）----
ASTOCK_CA_SYNC_WEEKDAY=4
ASTOCK_CA_SYNC_TIME=23:00
EOF
echo "[OK] wrote $ENV_FILE"

# serve() 启动时加载 <项目根>/.env（已有环境变量优先），PM2 模式靠它注入
# overlay/调度/治理配置；与 deploy/astock.env 保持同一份内容。
if [[ -f "$APP_ROOT/.env" ]]; then
  echo "[WARN] $APP_ROOT/.env 已存在，未覆盖（请手工合并 overlay/调度/治理配置）"
elif [[ -n "$MARKET_DATA_ROOT_VAL" ]]; then
  cp "$ENV_FILE" "$APP_ROOT/.env"
  echo "[OK] wrote $APP_ROOT/.env (serve() 加载源)"
else
  echo "[WARN] 未提供 --market-data-root，未生成 .env（production 下服务将拒绝启动，请先配置）"
fi

# ---- TUSHARE_TOKEN 检查（缺失仅警告，不阻断安装）----
if [[ -z "${TUSHARE_TOKEN:-}" ]] && ! grep -q '^TUSHARE_TOKEN=' "$ENV_FILE" 2>/dev/null; then
  echo
  echo "============================================================"
  echo "[WARN] 未检测到 TUSHARE_TOKEN（环境变量与 $ENV_FILE 中均未配置）"
  echo "[WARN] tushare 数据同步 / 因子同步将失败！"
  echo "[WARN]"
  echo "[WARN] 配置方式（二选一）："
  echo "[WARN]   1) 写入 $ENV_FILE 一行: TUSHARE_TOKEN=你的token"
  echo "[WARN]   2) 启动前导出: export TUSHARE_TOKEN=你的token"
  echo "[WARN]"
  echo "[WARN] Token 获取: https://tushare.pro 个人主页"
  echo "[WARN] 不影响本次安装，可稍后补配后重启服务。"
  echo "============================================================"
  echo
fi

# 启动参数
EXTRA_ARGS="--host $HOST --port $PORT --storage $STORAGE"
if [[ -n "$TDX_ROOT" ]]; then
  EXTRA_ARGS="$EXTRA_ARGS --tdx-root $TDX_ROOT"
fi

START_CMD="$PY -m wtpy.apps.astock serve $EXTRA_ARGS"

# 生成 PM2 ecosystem（env 从 $ENV_FILE 展开，保证 overlay/调度/治理变量对进程可见）
ENV_BLOCK=""
while IFS='=' read -r k v; do
  case "$k" in ''|\#*) continue ;; esac
  v="${v//\\/\\\\}"          # JSON 字符串转义反斜杠
  ENV_BLOCK="$ENV_BLOCK"$'\n'"        ${k}: \"${v}\","
done < "$ENV_FILE"
cat >"$PM2_ECO" <<EOF
/**
 * PM2 配置 — 不修改业务代码，直接拉起 uvicorn/FastAPI
 * 使用: pm2 start deploy/ecosystem.config.cjs
 * 日志: pm2 logs astock-serve
 */
module.exports = {
  apps: [
    {
      name: "astock-serve",
      cwd: "$APP_ROOT",
      script: "$PY",
      args: "-m wtpy.apps.astock serve $EXTRA_ARGS",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 30,
      min_uptime: "5s",
      max_memory_restart: "3500M",
      env: {$ENV_BLOCK
        PYTHONPATH: "$APP_ROOT",
        PYTHONUNBUFFERED: "1",
        TZ: "Asia/Shanghai",
        TUSHARE_TOKEN: process.env.TUSHARE_TOKEN || "",
      },
      // 避免与现有 PM2 应用争抢：固定名，不 watch
      watch: false,
      time: true,
    },
  ],
};
EOF
echo "[OK] wrote $PM2_ECO"

# 生成 systemd unit（需 root 安装到 /etc）
cat >"$UNIT_OUT" <<EOF
[Unit]
Description=AStock FastAPI console (wtpy.apps.astock)
After=network.target

[Service]
Type=simple
WorkingDirectory=$APP_ROOT
Environment=PYTHONPATH=$APP_ROOT
Environment=PYTHONUNBUFFERED=1
EnvironmentFile=-$ENV_FILE
ExecStart=$PY -m wtpy.apps.astock serve $EXTRA_ARGS
Restart=on-failure
RestartSec=5
# 限制：按机器改
# MemoryMax=12G

[Install]
WantedBy=multi-user.target
EOF
echo "[OK] wrote $UNIT_OUT"

# 快捷启动脚本
START_SH="$APP_ROOT/deploy/start_foreground.sh"
cat >"$START_SH" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$APP_ROOT"
export PYTHONPATH="$APP_ROOT"
export PYTHONUNBUFFERED=1
exec "$PY" -m wtpy.apps.astock serve $EXTRA_ARGS
EOF
chmod +x "$START_SH" 2>/dev/null || true
echo "[OK] wrote $START_SH"

# smoke import
if [[ $DRY_RUN -eq 0 ]]; then
  if "$PY" -c "import fastapi,uvicorn,numpy,pandas; print('deps ok')" 2>/dev/null; then
    echo "[OK] 核心依赖 import 通过"
  else
    echo "[FAIL] 核心依赖 import 失败，请检查 Python 版本与 pip 日志"
    exit 1
  fi
  if ! "$PY" -c "import openpyxl" 2>/dev/null; then
    echo "[WARN] openpyxl 未安装（导出 Excel/卦象导入会失败），尝试补装..."
    "$PIP" install openpyxl -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com || \
      "$PIP" install openpyxl || true
  fi
fi

echo
echo "======== 按 mode 启用常驻 ========"
case "$MODE" in
  pm2)
    if ! command -v pm2 >/dev/null 2>&1; then
      echo "[FAIL] 未安装 pm2。先: npm install -g pm2"
      exit 1
    fi
    # 若已存在同名则重启
    if pm2 describe astock-serve >/dev/null 2>&1; then
      run "pm2 delete astock-serve || true"
    fi
    run "pm2 start \"$PM2_ECO\""
    run "pm2 save"
    echo
    echo "[OK] PM2 已启动 astock-serve"
    echo "  状态: pm2 status"
    echo "  日志: pm2 logs astock-serve"
    echo "  开机: pm2 startup   # 按提示执行 sudo 命令后再 pm2 save"
    echo "  访问: http://服务器IP:$PORT/  （若 HOST=127.0.0.1 需 Nginx 反代或改 --host 0.0.0.0）"
    ;;
  systemd)
    echo "请用 root 安装 unit（不会自动 sudo，避免误改系统）："
    echo "  sudo cp $UNIT_OUT /etc/systemd/system/astock-serve.service"
    echo "  sudo systemctl daemon-reload"
    echo "  sudo systemctl enable --now astock-serve"
    echo "  sudo systemctl status astock-serve"
    echo "  journalctl -u astock-serve -f"
    if [[ $DRY_RUN -eq 0 && "$(id -u)" -eq 0 ]]; then
      cp "$UNIT_OUT" /etc/systemd/system/astock-serve.service
      systemctl daemon-reload
      systemctl enable --now astock-serve
      systemctl status astock-serve --no-pager || true
    fi
    ;;
  venv-only)
    echo "虚拟环境已就绪。前台试跑："
    echo "  $START_SH"
    echo "或："
    echo "  $START_CMD"
    ;;
  *)
    echo "[FAIL] unknown mode: $MODE"
    exit 1
    ;;
esac

echo
echo "安装配置完成。业务代码未改动。"
echo "若端口冲突: 重新执行 --port 新端口"
echo "若数据缺失: 同步本机 storage/astock 到 $STORAGE"
